### ISSUE TITLE
32-bit installer file signature invalid or corrupt

### ISSUE THREAD

**Issue by dpitic** [elvirbrk/NoteHighlight2016#13]
After I download the 32-bit MSI and Microsoft Edge completes the security scan, I get a warning stating that the signature is invalid or corrupt.  This precludes me from installing the program.  Do you plan to sign the file with a valid signature?

**Comment by elvirbrk** [comment]
Unfortunately, I don't think I can do much about it until Microsoft fixes it. As you can check by yourself, MSI files are signed by Visual Studio using Microsoft certificate (and not some certificate I can provide), but it is using expired certificate for signing, and that's why you get a warning.
So you have couple of options:
- Ignore warning
- Download source and VS 2015, and build it yourself
- Wait for Microsoft fix
