### ISSUE TITLE
Inserting new codes in position

### ISSUE THREAD

**Issue by tommyvuh** [elvirbrk/NoteHighlight2016#38]
![image](https://user-images.githubusercontent.com/24283779/35448409-11c6aa54-026f-11e8-8400-39e37b7fbed8.png)
![image](https://user-images.githubusercontent.com/24283779/35448443-2e67585c-026f-11e8-926d-0ef5f86d5762.png)
![image](https://user-images.githubusercontent.com/24283779/35448453-3618d968-026f-11e8-89f4-d7c3d325b2e2.png)

When inserting new codes, I find that it will always place everything at the top outside of the current textbox and in a new one and not where the cursor is.

**Comment by elvirbrk** [comment]
It's a feature :)
Existing outline will be used only if some existing text is selected for formatting, otherwise new outline will be created.
As a workaround, you could just enter couple of letters there under Chapter 10, select those letters for formatting and then just replace them with your code.
